; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rivermote]
platform = espressif32
board = esp32s3box
framework = arduino
lib_deps = 
	h2zero/NimBLE-Arduino@^2.3.6
	milesburton/DallasTemperature@^4.0.4
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
	sparkfun/SparkFun AS726X@^2.0.1
	vshymanskyy/StreamDebugger@^1.0.1
	vshymanskyy/TinyGSM@^0.12.0
	lewisxhe/XPowersLib@^0.3.0
build_flags = 
	-DRIVERMOTE
	-DBOARD_HAS_PSRAM
	-DICM_20948_USE_DMP
	-DXPOWERS_CHIP_AXP2101
	-DTINY_GSM_MODEM_SIM7080
	-DTINY_GSM_RX_BUFFER=1024
	-DCONFIG_BT_BLE_50_FEATURES_SUPPORTED
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
upload_speed = 921600
monitor_speed = 115200

[env:minimote]
platform = espressif32
board = esp32s3box
framework = arduino
lib_deps = 
	h2zero/NimBLE-Arduino@^2.3.6
	milesburton/DallasTemperature@^4.0.4
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
	sparkfun/SparkFun AS726X@^2.0.1
	vshymanskyy/StreamDebugger@^1.0.1
	vshymanskyy/TinyGSM@^0.12.0
	lewisxhe/XPowersLib@^0.3.0
build_flags = 
	-DMINIMOTE
	-DBOARD_HAS_PSRAM
	-DICM_20948_USE_DMP
	-DXPOWERS_CHIP_AXP2101
	-DTINY_GSM_MODEM_SIM7080
	-DTINY_GSM_RX_BUFFER=1024
	-DCONFIG_BT_BLE_50_FEATURES_SUPPORTED
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
upload_speed = 921600
monitor_speed = 115200
